name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Conan
      id: conan
      uses: turtlebrowser/get-conan@v1.0
    - name: Conan Version
      run: echo "${{ steps.conan.outputs.version}}"
    - name: Get latest G++/GCC version
      run: brew install gcc@11
    - name: Set CXX=g++-11
      run: echo "CXX=g++-11" >> $GITHUB_ENV
    - name: Set C=gcc-11
      run: echo "C=gcc-11" >> $GITHUB_ENV
    - name: Create default profile
      run: conan profile new default --detect
    - name: Update profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} --install-folder=${{github.workspace}}/build
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Run tests
      run: ${{github.workspace}}/build/tests
